#!/usr/bin/dash
mount -nt devtmpfs none dev
mount -nt proc proc proc
mount -nt sysfs sysfs /sys
mkdir dev/pts
mount -nt devpts devpts /dev/pts
for m in $(find /lib/modules -name '*.ko'); do modprobe $(basename -s .ko $m); done
setfont /etc/font.psf
loadkeys /etc/keys.kmap
export LANG=ru_RU.UTF-8
while true; do /usr/bin/dash; done
